import "server-only";

import { randomUUID } from "node:crypto";

import { importJWK, SignJWT } from "jose";

import { loadActiveSigningKeyMaterial } from "./signing-key";

/**
 * Audience claim that aimer-web's `verifyContextToken` requires.
 *
 * Codified here as a constant — and not as a string literal in the
 * route layer — so a typo cannot drift the claim away from what the
 * verifier expects.  Per patio#556 §6.6 / aimer-web Discussion #4 §4.3.
 */
export const AIMER_CONTEXT_TOKEN_AUDIENCE = "aimer-web";

/**
 * Decoded shape of the context-token JWS payload.  The route layer
 * populates every field — the signing library does not invent values.
 *
 * - `iss` and `aice_id` are the same configured `aice_id` from the
 *   Aimer integration system settings (Sub-7.2.AB).
 * - `aud` MUST equal {@link AIMER_CONTEXT_TOKEN_AUDIENCE}.
 * - `sub` is the stable per-account identifier (`session.accountId`).
 * - `customer_ids` is a single-element array of the resolved
 *   customer's `external_key`.  Never the internal numeric `id`.
 * - `iat` / `exp` are seconds since epoch; the canonical TTL is 60s.
 * - `jti` is a UUID generated by {@link generateContextTokenJti}.
 */
export interface ContextTokenPayload {
  iss: string;
  aud: string;
  sub: string;
  aice_id: string;
  customer_ids: string[];
  iat: number;
  exp: number;
  jti: string;
}

/** Generate a fresh `jti` claim for a context token. */
export function generateContextTokenJti(): string {
  return randomUUID();
}

/**
 * Sign a context token using the active Aimer signing key.
 *
 * Produces an ES256 JWS in compact serialization with the active
 * `kid` set in the protected header.  Throws when no active signing
 * key is available — the route layer must check the setup status
 * (Sub-7.2.AB) before calling, so this is treated as a programming
 * error rather than a recoverable "503 not configured" path.
 */
export async function signContextToken(
  payload: ContextTokenPayload,
): Promise<string> {
  const keyMaterial = loadActiveSigningKeyMaterial();
  if (!keyMaterial) {
    throw new Error(
      "No active Aimer signing key. Verify integration setup before signing.",
    );
  }
  const privateKey = await importJWK(
    keyMaterial.privateJwk,
    keyMaterial.algorithm,
  );

  return new SignJWT({
    aice_id: payload.aice_id,
    customer_ids: payload.customer_ids,
  })
    .setProtectedHeader({ alg: keyMaterial.algorithm, kid: keyMaterial.kid })
    .setIssuer(payload.iss)
    .setAudience(payload.aud)
    .setSubject(payload.sub)
    .setIssuedAt(payload.iat)
    .setExpirationTime(payload.exp)
    .setJti(payload.jti)
    .sign(privateKey);
}
