import "server-only";

import { randomUUID } from "node:crypto";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

import type { JWK } from "jose";
import { calculateJwkThumbprint, exportJWK, generateKeyPair } from "jose";

import { getDataDir } from "@/lib/auth/data-dir";

// ── Types ───────────────────────────────────────────────────────

/**
 * On-disk shape of `aimer-context-signing.json`.
 *
 * The file holds at most three slots: an `active` slot (current
 * signing key), a `pending` slot (newly generated key awaiting
 * `Switch` after the operator has registered the new kid on
 * aimer-web's trust registry), and a `previous` slot (the kid
 * superseded by the most recent `Switch`, retained for a short
 * window to absorb in-flight context-token verification races on
 * aimer-web's side via redelivery).
 */
interface AimerSigningKeyFile {
  /** Currently signing context tokens. Required once the file exists. */
  active: AimerSigningKeyEntry;
  /** Generated by `Rotate`, becomes `active` on `Switch`. */
  pending?: AimerSigningKeyEntry | null;
  /**
   * The kid demoted by the most recent `Switch`.  Retained until the
   * `recommended_deactivate_at` timestamp passes; then the operator
   * (or a future automation) can call `Deactivate` to remove it.
   */
  previous?: AimerSigningKeyEntry | null;
}

interface AimerSigningKeyEntry {
  kid: string;
  algorithm: string;
  privateKey: JWK;
  publicKey: JWK;
  /** ISO timestamp when this kid was generated. */
  createdAt: string;
  /** ISO timestamp at which a rotation is recommended. */
  recommendedRotationAt: string;
  /**
   * For the `previous` slot, the earliest time at which Deactivate
   * is auto-eligible.  Computed as the switch time plus
   * `context-token TTL (60s) + clock-skew margin`.  Absent on
   * `active` and `pending`.
   */
  recommendedDeactivateAt?: string;
}

export interface AimerSigningKeyPublicEntry {
  kid: string;
  algorithm: string;
  publicJwk: JWK;
  thumbprintBase64Url: string;
  thumbprintHexColons: string;
  createdAt: string;
  recommendedRotationAt: string;
  recommendedDeactivateAt?: string;
}

export type AimerSigningKeyState =
  | "empty"
  | "active_only"
  | "active_and_pending"
  | "active_and_previous";

export interface AimerSigningKeyStatus {
  state: AimerSigningKeyState;
  active: AimerSigningKeyPublicEntry | null;
  pending: AimerSigningKeyPublicEntry | null;
  previous: AimerSigningKeyPublicEntry | null;
  /** True when the on-disk file mode drifted from `0600`. */
  filePermissionAlert: boolean;
  /** Human-readable mode actually observed (e.g. "0644") for the alert. */
  observedFilePermission: string | null;
}

// ── Constants ───────────────────────────────────────────────────

const DEFAULT_ALGORITHM = "ES256";
const ROTATION_RECOMMENDATION_DAYS = 365;

/**
 * Default retention window for the `previous` slot, expressed in
 * milliseconds.  Sized to context-token TTL (60s) plus a generous
 * clock-skew / redelivery margin (5 minutes total).  Configurable
 * via the `AIMER_SIGNING_KEY_PREV_RETENTION_MS` env var so e2e tests
 * can collapse the window.
 */
function previousRetentionMs(): number {
  const raw = process.env.AIMER_SIGNING_KEY_PREV_RETENTION_MS;
  if (raw && raw.length > 0) {
    const parsed = Number(raw);
    if (Number.isFinite(parsed) && parsed >= 0) return parsed;
  }
  return 5 * 60 * 1000;
}

// ── File paths ──────────────────────────────────────────────────

function keysDir(): string {
  // Match jwt-keys.ts: build via array-join so the static path doesn't
  // get pulled into the Next.js File Tracer's standalone bundle.
  return [getDataDir(), "keys"].join(path.sep);
}

function defaultKeyBasename(): string {
  const stem = ["aimer", "context", "signing"].join("-");
  return [stem, "json"].join(".");
}

function keyFilePath(): string {
  return [keysDir(), defaultKeyBasename()].join(path.sep);
}

// ── File I/O ────────────────────────────────────────────────────

function readKeyFile(): AimerSigningKeyFile | null {
  try {
    const content = readFileSync(keyFilePath(), "utf8");
    const parsed = JSON.parse(content) as AimerSigningKeyFile;
    if (!parsed?.active?.kid) return null;
    return parsed;
  } catch {
    return null;
  }
}

function writeKeyFile(data: AimerSigningKeyFile): void {
  const target = keyFilePath();
  const dir = path.dirname(target);

  mkdirSync(dir, { recursive: true, mode: 0o700 });
  try {
    chmodSync(dir, 0o700);
  } catch {
    // best-effort on platforms that don't honor POSIX perms
  }

  // Atomic write — temp file + rename — so a partial write never
  // leaves a half-written key on disk.  See #437 acceptance criteria.
  const tmpPath = `${target}.${process.pid}.${randomUUID()}.tmp`;
  writeFileSync(tmpPath, JSON.stringify(data, null, 2), {
    encoding: "utf8",
    mode: 0o600,
  });

  // writeFileSync's `mode` only applies on creation; force perms
  // afterwards so the umask cannot loosen them.  Fail closed if we
  // cannot tighten — leaving a 0644 private-key file would defeat
  // the wrong-permission detection that runs on the next admin
  // reload.
  try {
    chmodSync(tmpPath, 0o600);
  } catch (cause) {
    try {
      unlinkSync(tmpPath);
    } catch {
      // ignore — the temp file is the bigger problem
    }
    throw new Error(
      "Failed to set 0600 perms on Aimer signing key file. Refusing to write a key with looser permissions.",
      { cause },
    );
  }

  // Confirm the perms before rename — defense in depth on platforms
  // where chmod silently drops bits.
  const tmpMode = statSync(tmpPath).mode & 0o777;
  if (tmpMode !== 0o600) {
    try {
      unlinkSync(tmpPath);
    } catch {
      // ignore
    }
    throw new Error(
      `Aimer signing key tmp file has mode 0${tmpMode.toString(8).padStart(3, "0")}, expected 0600. Aborting.`,
    );
  }

  renameSync(tmpPath, target);
}

function fileMode(): string | null {
  try {
    const mode = statSync(keyFilePath()).mode & 0o777;
    return `0${mode.toString(8).padStart(3, "0")}`;
  } catch {
    return null;
  }
}

function isFileModeOk(): boolean {
  const mode = fileMode();
  return mode === null || mode === "0600";
}

// ── Public utilities ────────────────────────────────────────────

/**
 * Compute the RFC 7638 SHA-256 Thumbprint of a public JWK in two
 * presentation formats.  The base64url form is canonical (43 chars,
 * no padding, encodes the full 32-byte SHA-256).  The colon-separated
 * hex form is the same 32 bytes rendered as 64 hex chars grouped in
 * 4-byte (8 hex char) blocks separated by `:` — a visual aid for
 * verbal / mental comparison.
 *
 * Both formats encode the full SHA-256.  Only the rendering differs.
 */
export async function computeJwkThumbprintFormats(
  publicJwk: JWK,
): Promise<{ base64url: string; hexColons: string }> {
  // `calculateJwkThumbprint` returns the canonical base64url form.
  // It strips the SHA-256 to its 32 raw bytes and re-encodes; we
  // decode it back to bytes here to render the hex form so both
  // representations reference the same byte sequence.
  const base64url = await calculateJwkThumbprint(publicJwk, "sha256");
  const bytes = base64UrlDecode(base64url);
  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join(
    "",
  );
  const groups: string[] = [];
  for (let i = 0; i < hex.length; i += 8) {
    groups.push(hex.slice(i, i + 8));
  }
  return { base64url, hexColons: groups.join(":") };
}

function base64UrlDecode(value: string): Uint8Array {
  const pad = "=".repeat((4 - (value.length % 4)) % 4);
  const base64 = (value + pad).replace(/-/g, "+").replace(/_/g, "/");
  return Uint8Array.from(Buffer.from(base64, "base64"));
}

function isoNow(): string {
  return new Date().toISOString();
}

function isoFromNowDays(days: number): string {
  return new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();
}

async function generateEntry(
  algorithm = DEFAULT_ALGORITHM,
): Promise<AimerSigningKeyEntry> {
  const { privateKey, publicKey } = await generateKeyPair(algorithm, {
    extractable: true,
  });
  const kid = randomUUID();
  const privateJwk = await exportJWK(privateKey);
  const publicJwk = await exportJWK(publicKey);
  privateJwk.kid = kid;
  publicJwk.kid = kid;

  return {
    kid,
    algorithm,
    privateKey: privateJwk,
    publicKey: publicJwk,
    createdAt: isoNow(),
    recommendedRotationAt: isoFromNowDays(ROTATION_RECOMMENDATION_DAYS),
  };
}

async function toPublicEntry(
  entry: AimerSigningKeyEntry,
): Promise<AimerSigningKeyPublicEntry> {
  const { base64url, hexColons } = await computeJwkThumbprintFormats(
    entry.publicKey,
  );
  return {
    kid: entry.kid,
    algorithm: entry.algorithm,
    publicJwk: entry.publicKey,
    thumbprintBase64Url: base64url,
    thumbprintHexColons: hexColons,
    createdAt: entry.createdAt,
    recommendedRotationAt: entry.recommendedRotationAt,
    recommendedDeactivateAt: entry.recommendedDeactivateAt,
  };
}

function deriveState(file: AimerSigningKeyFile | null): AimerSigningKeyState {
  if (!file) return "empty";
  if (file.pending?.kid) return "active_and_pending";
  if (file.previous?.kid) return "active_and_previous";
  return "active_only";
}

// ── Public API: read ────────────────────────────────────────────

/**
 * Public, render-safe view of the on-disk signing key file.  Returns
 * the rotation state, public JWKs, and thumbprints for every slot.
 * Never returns private key bytes.
 */
export async function getAimerSigningKeyStatus(): Promise<AimerSigningKeyStatus> {
  const file = readKeyFile();
  const state = deriveState(file);

  const observedMode = fileMode();
  const filePermissionAlert = !isFileModeOk();

  if (!file) {
    return {
      state,
      active: null,
      pending: null,
      previous: null,
      filePermissionAlert,
      observedFilePermission: observedMode,
    };
  }

  const active = await toPublicEntry(file.active);
  const pending = file.pending ? await toPublicEntry(file.pending) : null;
  const previous = file.previous ? await toPublicEntry(file.previous) : null;

  return {
    state,
    active,
    pending,
    previous,
    filePermissionAlert,
    observedFilePermission: observedMode,
  };
}

/** True when an active signing key exists. Used by setup status. */
export function hasActiveAimerSigningKey(): boolean {
  return readKeyFile() !== null;
}

/** Look up a public entry by `kid`, searching all three slots. */
export async function getAimerVerificationKey(
  kid: string,
): Promise<AimerSigningKeyPublicEntry | null> {
  const file = readKeyFile();
  if (!file) return null;
  if (file.active.kid === kid) return toPublicEntry(file.active);
  if (file.pending?.kid === kid) return toPublicEntry(file.pending);
  if (file.previous?.kid === kid) return toPublicEntry(file.previous);
  return null;
}

/**
 * Internal: load the active private key (for context-token signing
 * by Sub-7.2.D).  Server-side only — callers must never expose the
 * returned JWK over HTTP.
 */
export function loadActiveSigningKeyMaterial(): {
  kid: string;
  algorithm: string;
  privateJwk: JWK;
} | null {
  const file = readKeyFile();
  if (!file) return null;
  return {
    kid: file.active.kid,
    algorithm: file.active.algorithm,
    privateJwk: file.active.privateKey,
  };
}

/** True when the on-disk perms drifted from 0600. Boot logs use this. */
export function checkFilePermissionsOk(): {
  ok: boolean;
  observed: string | null;
} {
  const observed = fileMode();
  return { ok: isFileModeOk(), observed };
}

// ── Public API: write / state machine ───────────────────────────

/**
 * Initial generation.  Only allowed when the file does not exist
 * yet — overwriting an active key would invalidate every context
 * token already accepted by aimer-web.  Use {@link rotateAimerSigningKey}
 * to mint a new kid alongside the existing active one.
 */
export async function generateAimerSigningKey(
  algorithm = DEFAULT_ALGORITHM,
): Promise<{ kid: string }> {
  if (readKeyFile() !== null) {
    throw new Error(
      "Aimer signing key already exists. Use rotate to mint a new kid.",
    );
  }
  const active = await generateEntry(algorithm);
  writeKeyFile({ active });
  return { kid: active.kid };
}

/**
 * Mint a new keypair and stage it as `pending`.  Allowed only when
 * the state is `active_only` — refusing during `active_and_pending`
 * avoids minting a third concurrent kid before `Switch`, and during
 * `active_and_previous` the operator must `Deactivate` the previous
 * kid before starting a fresh rotation.
 */
export async function rotateAimerSigningKey(
  algorithm = DEFAULT_ALGORITHM,
): Promise<{ kid: string }> {
  const file = readKeyFile();
  if (!file) {
    throw new Error("No active Aimer signing key to rotate from.");
  }
  if (file.pending?.kid) {
    throw new Error(
      "Rotation already in progress. Switch to the pending kid (or wait for the operator to confirm registration on aimer-web) before rotating again.",
    );
  }
  if (file.previous?.kid) {
    throw new Error(
      "Previous kid is still retained from a recent Switch. Deactivate the previous kid before starting a new rotation.",
    );
  }
  const pending = await generateEntry(algorithm);
  writeKeyFile({ ...file, pending });
  return { kid: pending.kid };
}

/**
 * Promote the `pending` kid to `active` and demote the old `active`
 * kid to `previous`.  The caller must have set `confirmRegistered:
 * true` to assert the new kid is already registered on aimer-web's
 * trust registry; otherwise context tokens signed by the new kid
 * would be rejected by the receiver.
 */
export async function switchAimerSigningKey(params: {
  confirmRegistered: boolean;
}): Promise<{ activeKid: string; previousKid: string }> {
  if (!params.confirmRegistered) {
    throw new Error(
      "Switch requires confirmation that the new kid is registered on aimer-web's trust registry.",
    );
  }

  const file = readKeyFile();
  if (!file) {
    throw new Error("No Aimer signing key file to switch.");
  }
  if (!file.pending?.kid) {
    throw new Error("No pending kid to switch to. Run rotate first.");
  }

  const previousEntry: AimerSigningKeyEntry = {
    ...file.active,
    recommendedDeactivateAt: new Date(
      Date.now() + previousRetentionMs(),
    ).toISOString(),
  };

  writeKeyFile({
    active: file.pending,
    pending: null,
    previous: previousEntry,
  });

  return {
    activeKid: file.pending.kid,
    previousKid: file.active.kid,
  };
}

/**
 * Drop the `previous` slot.  Allowed only after the
 * `recommendedDeactivateAt` window has elapsed — context tokens
 * signed by the previous kid before the switch may still be in
 * flight via aimer-web's redelivery, and the receiver verifies via
 * `trust_registry`'s cached public key (not via the private key
 * here), so the delay protects against a brief race window.
 *
 * Pass `{ force: true }` to bypass the timer (admin override).
 */
export function deactivateAimerSigningPreviousKey(
  params: { force?: boolean } = {},
): { previousKid: string } {
  const file = readKeyFile();
  if (!file) {
    throw new Error("No Aimer signing key file present.");
  }
  if (!file.previous?.kid) {
    throw new Error("No previous kid to deactivate.");
  }

  if (!params.force) {
    const recommendedAt = file.previous.recommendedDeactivateAt;
    if (recommendedAt) {
      const due = Date.parse(recommendedAt);
      if (Number.isFinite(due) && Date.now() < due) {
        throw new Error(
          `Previous kid retention window has not elapsed (recommended deactivate at ${recommendedAt}). Pass force to override.`,
        );
      }
    }
  }

  const previousKid = file.previous.kid;
  writeKeyFile({ active: file.active, pending: file.pending ?? null });
  return { previousKid };
}

// ── Test helpers ────────────────────────────────────────────────

/** Remove the on-disk file. Test-only. */
export function deleteAimerSigningKeyFile(): void {
  try {
    unlinkSync(keyFilePath());
  } catch {
    // not present — no-op
  }
}

/** Resolve the on-disk path. Used by boot-time perm warnings and tests. */
export function aimerSigningKeyFilePath(): string {
  return keyFilePath();
}

/** Force the file's mode for tests covering perm-drift detection. */
export function chmodAimerSigningKeyFileForTest(mode: number): void {
  if (existsSync(keyFilePath())) {
    chmodSync(keyFilePath(), mode);
  }
}
