import { expect, request as playwrightRequest, test } from "@playwright/test";

import { closeAdminAgent, mockServerSession } from "./mock-server-admin";
import { mockServerUrl } from "./mock-server-state";

/**
 * Smoke check that proves the mock REview harness is wired end to end:
 *
 *   1. The mock REview GraphQL server brought up by `global-setup.ts`
 *      responds to introspection and to the canned `eventList` operation
 *      over HTTPS + mTLS using the test CA generated by the harness.
 *   2. Specs running in a worker process can register a scenario-specific
 *      stub via the mock server's admin HTTP endpoint — the mechanism that
 *      feature specs use from their `test.beforeAll` hooks.
 *
 * Browser-launch and dev-server reachability are already guaranteed by
 * Playwright's `webServer` health check (it polls the app URL before any
 * test runs), so they are not re-asserted here. Feature E2E scenarios live
 * in their own spec files and are owned by the corresponding feature issues.
 */
function tlsRequestContext() {
  const reviewOrigin = mockServerUrl("review").replace(/\/graphql$/, "");
  return playwrightRequest.newContext({
    clientCertificates: [
      {
        origin: reviewOrigin,
        certPath: process.env.MTLS_CERT_PATH,
        keyPath: process.env.MTLS_KEY_PATH,
      },
    ],
    ignoreHTTPSErrors: true,
    extraHTTPHeaders: { "Content-Type": "application/json" },
  });
}

test.describe("test harness wiring", () => {
  const session = mockServerSession();

  test.afterAll(async () => {
    await session.clear();
    await closeAdminAgent();
  });

  test("mock REview GraphQL server responds to introspection", async () => {
    const ctx = await tlsRequestContext();
    try {
      const res = await ctx.post(mockServerUrl("review"), {
        data: { query: "{ __schema { queryType { name } } }" },
      });
      expect(res.status()).toBe(200);
      const body = await res.json();
      expect(body.errors).toBeUndefined();
      expect(body.data.__schema.queryType.name).toBe("Query");
    } finally {
      await ctx.dispose();
    }
  });

  test("mock REview GraphQL server returns the manifest-preloaded eventList", async () => {
    const ctx = await tlsRequestContext();
    try {
      // Manifest entries register stubs keyed to their declared `variables`,
      // so the request must send the same shape `{ filter: {}, first: 10 }`
      // that `manifest.json` declares for `eventList`. Different variables
      // would (correctly) miss the manifest stub.
      const res = await ctx.post(mockServerUrl("review"), {
        data: {
          query: `query Q($filter: EventListFilterInput!, $first: Int) {
            eventList(filter: $filter, first: $first) {
              totalCount
              edges { cursor }
              pageInfo { hasNextPage }
            }
          }`,
          variables: { filter: {}, first: 10 },
        },
      });
      expect(res.status()).toBe(200);
      const body = await res.json();
      expect(body.errors).toBeUndefined();
      expect(body.data.eventList.totalCount).toBe("0");
      expect(body.data.eventList.edges).toEqual([]);
    } finally {
      await ctx.dispose();
    }
  });

  test("specs can register a scenario stub via the admin endpoint", async () => {
    // The admin endpoint no longer accepts inline fixture JSON — every
    // fixture payload must come from a manifest-declared file so the
    // pre-test preflight validates it. `kind: "errors"` exercises the
    // admin-registration round-trip without introducing a new fixture.
    await session.registerStub({
      operation: "indicatorList",
      response: {
        kind: "errors",
        errors: [{ message: "harness-stub-error" }],
      },
    });

    const ctx = await tlsRequestContext();
    try {
      const res = await ctx.post(mockServerUrl("review"), {
        data: { query: "{ indicatorList { name } }" },
      });
      expect(res.status()).toBe(200);
      const body = await res.json();
      expect(body.errors?.[0]?.message).toBe("harness-stub-error");
    } finally {
      await ctx.dispose();
    }
  });
});
