-- Low-and-slow Story sweep watermark (issue #701).
--
-- The hourly low-and-slow sweep (`src/lib/triage/baseline/lowslow-sweep.ts`)
-- mirrors the cadence step-(f) finalization protocol but over a 24h
-- window, decoupled from the 15-minute cadence. It needs its own
-- monotonic watermark so a sweep tick knows "everything strictly
-- earlier than X has already been considered for low-and-slow
-- finalization" — exactly the role `story_finalized_through`
-- (migration 0008) plays for the cadence path.
--
-- Additive column only. The sweep's horizon is bounded by cadence's
-- own settled watermark (`story_finalized_through`), so this column is
-- advanced with `GREATEST(...)` and never moves backward — see
-- `advanceLowslowWatermark` in `src/lib/triage/story/repository.ts`.
--
-- No `event_group` schema change here: the `correlation_key` column
-- (and the re-scoped dedup indexes) already landed with migration 0024
-- (#694). R6 rows carry `correlation_key = NULL` and dedup on the
-- re-scoped `event_group_auto_dedup_idx`, exactly like R1/R3.
--
-- The optional `selector_tags` GIN index that the Sweep-performance
-- acceptance criterion contemplates is NOT added here: the EXPLAIN
-- ANALYZE measurement did not show the phase-1 `selector_tags &&`
-- overlap as the dominant cost on a representative corpus (the
-- two-phase per-asset read rides the existing `event_time` and
-- `orig_addr` indexes), so the additive watermark column is the only
-- schema change this migration makes. Should a future measurement at
-- scale warrant it, the GIN index is a follow-up, migration-only
-- change with no callsite churn.
ALTER TABLE baseline_corpus_state
    ADD COLUMN IF NOT EXISTS lowslow_finalized_through TIMESTAMPTZ;
