import { z } from "zod";

import { formatSocketAddr, parseSocketAddr } from "../socket-addr";
import { fromToml, type TomlEntries, toToml } from "../toml";
import {
  ipAddressSchema,
  nodeHostnameSchema,
  noLeadingTrailingWhitespace,
  portSchema,
} from "../validation";
import { hydrateChecklist, normaliseChecklist } from "./empty-list";
import {
  GIGANTO_INGEST_PORT,
  MAX_PCAP_SIZE,
  type ServiceFormModule,
  STANDARD_PORTS,
} from "./types";

/**
 * Piglet (Sensor) configuration form.
 *
 * Authoritative spec: `decisions/node-field-catalog.md` ("Piglet").
 * The hardcoded fields below mirror aice-web's `PigletConfig`
 * serialisation as documented in the catalog. The wire-format
 * byte-compatibility fixtures
 * (`src/__tests__/lib/node/fixtures/sensor-*.toml`) are generated by
 * `tools/draft-capture/` — a Rust binary that pulls in `toml = "0.8"`
 * and the upstream `PigletConfig` struct verbatim, so the fixture
 * suite cross-checks our emitter against a different code path.
 */

export const PROTOCOLS_FOR_PIGLET = [
  "bootp",
  "conn",
  "dns",
  "ftp",
  "http",
  "https",
  "kerberos",
  "ldap",
  "mqtt",
  "nfs",
  "radius",
  "rdp",
  "smb",
  "smtp",
  "ssh",
] as const;
export type ProtocolForPiglet = (typeof PROTOCOLS_FOR_PIGLET)[number];

export const DUMP_ITEMS = ["pcap", "eml", "ftp", "http"] as const;
export type DumpItem = (typeof DUMP_ITEMS)[number];

export const DUMP_HTTP_CONTENT_TYPES = [
  "office",
  "exe",
  "pdf",
  "txt",
  "vbs",
] as const;
export type DumpHttpContentType = (typeof DUMP_HTTP_CONTENT_TYPES)[number];

export const SENSOR_HARDCODED = {
  dpdkArgs: "",
  srcMac: "00:00:00:00:00:00",
  dstMac: "00:00:00:00:00:00",
  dumpDir: "/opt/clumit/var/sensor",
  logPath: "/opt/clumit/log/sensor.log",
} as const;

export interface SensorFormValues {
  /** Data Store connection — IP. */
  dataStoreIp: string;
  /** Data Store connection — hostname (`giganto_name`). */
  dataStoreHostname: string;
  /** Data Store connection — port. */
  dataStorePort: number;
  /** Comma-separated by the UI; emitted in both dpdk_inputs/outputs. */
  pciBusAddresses: string[];
  protocols: ProtocolForPiglet[];
  ftpPorts: number[];
  httpPorts: number[];
  httpsPorts: number[];
  sshPorts: number[];
  dumpItems: DumpItem[];
  dumpHttpContentTypes: DumpHttpContentType[];
  pcapMaxSize: number;
}

export const sensorFormSchema = z.object({
  dataStoreIp: ipAddressSchema,
  dataStoreHostname: nodeHostnameSchema(),
  dataStorePort: portSchema,
  pciBusAddresses: z
    .array(z.string().refine(noLeadingTrailingWhitespace))
    .min(1, "At least one PCI Bus Address is required"),
  protocols: z.array(z.enum(PROTOCOLS_FOR_PIGLET)),
  ftpPorts: z.array(portSchema),
  httpPorts: z.array(portSchema),
  httpsPorts: z.array(portSchema),
  sshPorts: z.array(portSchema),
  dumpItems: z.array(z.enum(DUMP_ITEMS)),
  dumpHttpContentTypes: z.array(z.enum(DUMP_HTTP_CONTENT_TYPES)),
  pcapMaxSize: z.number({ error: "Must be a number" }).int().min(0).max(65535),
});

/**
 * Ensure every pinned `standard` port is present in `value`, preserving
 * the caller's order for any custom ports. The chip input renders the
 * standard ports as locked "(standard)" chips, so the form value must
 * include them — otherwise the wire payload would round-trip as missing
 * despite the chip claiming "(standard)". Centralising this in the
 * defaults / deserialise pair keeps the leaf input as a pure
 * presentation component (no mount-time `onChange` that would silently
 * dirty a freshly hydrated form).
 */
function withStandardPorts(
  value: readonly number[] | undefined,
  standard: readonly number[],
): number[] {
  const incoming = value ?? [];
  const standardSet = new Set(standard);
  const customs = incoming.filter((p) => !standardSet.has(p));
  return [...standard, ...customs];
}

export function defaultSensorValues(
  initial?: SensorFormValues | null,
): SensorFormValues {
  if (initial) {
    return {
      ...initial,
      ftpPorts: withStandardPorts(initial.ftpPorts, STANDARD_PORTS.ftp),
      httpPorts: withStandardPorts(initial.httpPorts, STANDARD_PORTS.http),
      httpsPorts: withStandardPorts(initial.httpsPorts, STANDARD_PORTS.https),
      sshPorts: withStandardPorts(initial.sshPorts, STANDARD_PORTS.ssh),
    };
  }
  return {
    dataStoreIp: "",
    dataStoreHostname: "",
    dataStorePort: GIGANTO_INGEST_PORT,
    pciBusAddresses: [],
    protocols: [...PROTOCOLS_FOR_PIGLET],
    ftpPorts: [...STANDARD_PORTS.ftp],
    httpPorts: [...STANDARD_PORTS.http],
    httpsPorts: [...STANDARD_PORTS.https],
    sshPorts: [...STANDARD_PORTS.ssh],
    dumpItems: ["pcap"],
    dumpHttpContentTypes: [...DUMP_HTTP_CONTENT_TYPES],
    pcapMaxSize: MAX_PCAP_SIZE,
  };
}

export function serialiseSensor(values: SensorFormValues): string {
  const protocols = normaliseChecklist(values.protocols, PROTOCOLS_FOR_PIGLET);
  const dumpItems = normaliseChecklist(values.dumpItems, DUMP_ITEMS);
  // `dump_http_content_types` is nested under the HTTP dump-item.
  // Once the user unchecks `http`, the UI hides the nested checkbox
  // group but RHF state retains the last selection — emitting that
  // stale list would silently keep a content-type filter active on
  // the wire even though the parent toggle is off. Force the wire
  // shape to "zero selected" (`Some([])`) in that case so hidden
  // state cannot leak; once `http` is re-enabled the user re-picks
  // the content types explicitly.
  const httpEnabled = values.dumpItems.includes("http");
  const dumpHttpContentTypes = httpEnabled
    ? normaliseChecklist(values.dumpHttpContentTypes, DUMP_HTTP_CONTENT_TYPES)
    : [];
  // Key order mirrors aice-web's `PigletConfig` struct declaration
  // order at commit `71c4623…`, which is the order Rust's `toml` crate
  // emits — see `tools/draft-capture/` for the reference generator.
  const entries: TomlEntries = [
    ["dpdk_args", SENSOR_HARDCODED.dpdkArgs],
    ["dpdk_inputs", values.pciBusAddresses],
    ["dpdk_outputs", values.pciBusAddresses],
    ["src_mac", SENSOR_HARDCODED.srcMac],
    ["dst_mac", SENSOR_HARDCODED.dstMac],
    ["dump_dir", SENSOR_HARDCODED.dumpDir],
    ["log_path", SENSOR_HARDCODED.logPath],
    ["dump_items", dumpItems],
    ["dump_http_content_types", dumpHttpContentTypes],
    [
      "giganto_ingest_srv_addr",
      formatSocketAddr(values.dataStoreIp, values.dataStorePort),
    ],
    ["giganto_name", values.dataStoreHostname],
    ["pcap_max_size", values.pcapMaxSize],
    ["protocols", protocols],
    ["http_ports", values.httpPorts],
    ["https_ports", values.httpsPorts],
    ["ssh_ports", values.sshPorts],
    ["ftp_ports", values.ftpPorts],
  ];
  return toToml(entries);
}

export function deserialiseSensor(toml: string): SensorFormValues {
  const raw = fromToml(toml);
  const { ip, port } = parseSocketAddr(
    (raw.giganto_ingest_srv_addr ?? "") as string,
    GIGANTO_INGEST_PORT,
  );
  const protocols = raw.protocols as readonly ProtocolForPiglet[] | undefined;
  const dumpItems = raw.dump_items as readonly DumpItem[] | undefined;
  const dumpHttpContentTypes = raw.dump_http_content_types as
    | readonly DumpHttpContentType[]
    | undefined;
  return {
    dataStoreIp: ip,
    dataStoreHostname: (raw.giganto_name ?? "") as string,
    dataStorePort: port,
    pciBusAddresses: (raw.dpdk_inputs ?? []) as string[],
    protocols: hydrateChecklist(protocols, PROTOCOLS_FOR_PIGLET),
    ftpPorts: withStandardPorts(raw.ftp_ports as number[], STANDARD_PORTS.ftp),
    httpPorts: withStandardPorts(
      raw.http_ports as number[],
      STANDARD_PORTS.http,
    ),
    httpsPorts: withStandardPorts(
      raw.https_ports as number[],
      STANDARD_PORTS.https,
    ),
    sshPorts: withStandardPorts(raw.ssh_ports as number[], STANDARD_PORTS.ssh),
    dumpItems: hydrateChecklist(dumpItems, DUMP_ITEMS),
    dumpHttpContentTypes: hydrateChecklist(
      dumpHttpContentTypes,
      DUMP_HTTP_CONTENT_TYPES,
    ),
    pcapMaxSize: (raw.pcap_max_size ?? MAX_PCAP_SIZE) as number,
  };
}

export const sensorModule: ServiceFormModule<SensorFormValues> = {
  defaults: defaultSensorValues,
  serialise: serialiseSensor,
  deserialise: deserialiseSensor,
};
